### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by Avi2427** [muralianand12345/Discord-Ticket-Bot#8]
(node:539) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:539) DeprecationWarning: MessageEmbed#addField is deprecated and will be removed in the next major update. Use MessageEmbed#addFields instead.
TypeError: Cannot read properties of undefined (reading 'set')
    at Object.execute (/home/runner/ticket-bot/handlers/commands/commands.js:16:29)
    at Client.<anonymous> (/home/runner/ticket-bot/bot.js:71:54)
    at Client.emit (node:events:525:35)
    at WebSocketManager.triggerClientReady (/home/runner/ticket-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:387:17)
    at WebSocketManager.checkShardsReady (/home/runner/ticket-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:370:10)
    at WebSocketShard.<anonymous> (/home/runner/ticket-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:200:16)
    at WebSocketShard.emit (node:events:513:28)
    at WebSocketShard.checkReady (/home/runner/ticket-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:181:12)
    at module.exports [as READY] (/home/runner/ticket-bot/node_modules/discord.js/src/client/websocket/handlers/READY.js:26:9)
    at WebSocketManager.handlePacket (/home/runner/ticket-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:354:31)

**Comment by muralianand12345** [comment]
It seems like that you have some problems with the slash commands. Make sure 2 things!
1. Not to use same command names for both slash and message commands
2. Make sure you have a valid slash command configuration.

**Comment by Avi2427** [comment]
i've checked im just used  your full src jus edited config files but im getting this error idk that becoz im using win to run the bot

**Comment by muralianand12345** [comment]
I'll fix it in next update.

**Comment by cowardtv** [comment]
happens to me as well... just launched the bot and i cant use anything. i suggest to fix this and give some tutorial on this bot its very complicated and no understanding exactcly what each thing does and how it works

**Comment by muralianand12345** [comment]
Yes this code is not friendly to edit and use. Just let me know what all the features you are expecting here or I'll just simplify the ticket bot code alone
